# Generated by Django 5.2.6 on 2025-09-21 09:14

import django.db.models.deletion
import maps.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Layout')),
                ('layout_type', models.CharField(choices=[('location', 'Mapa de Localização'), ('hydrographic', 'Mapa Hidrográfico'), ('relief', 'Mapa de Relevo'), ('hypsometric', 'Mapa Hipsométrico')], max_length=20, verbose_name='Tipo de Layout')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('template_config', models.JSONField(default=dict, verbose_name='Configuração do Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Layout de Mapa',
                'verbose_name_plural': 'Layouts de Mapas',
                'ordering': ['layout_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GISProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Projeto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gis_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projeto GIS',
                'verbose_name_plural': 'Projetos GIS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('output_format', models.CharField(choices=[('pdf', 'PDF'), ('png', 'PNG'), ('html', 'HTML')], max_length=10, verbose_name='Formato de Saída')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='Status')),
                ('output_file', models.FileField(blank=True, null=True, upload_to='generated_maps/', verbose_name='Arquivo Gerado')),
                ('generation_started_at', models.DateTimeField(auto_now_add=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_maps', to='maps.gisproject')),
            ],
            options={
                'verbose_name': 'Mapa Gerado',
                'verbose_name_plural': 'Mapas Gerados',
                'ordering': ['-generation_started_at'],
            },
        ),
        migrations.CreateModel(
            name='MapConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Título do Mapa')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subtítulo')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=maps.models.upload_to_logos, verbose_name='Logo')),
                ('primary_color', models.CharField(default='#2E8B57', max_length=7, verbose_name='Cor Primária')),
                ('secondary_color', models.CharField(default='#4682B4', max_length=7, verbose_name='Cor Secundária')),
                ('show_scale', models.BooleanField(default=True, verbose_name='Mostrar Escala')),
                ('show_north_arrow', models.BooleanField(default=True, verbose_name='Mostrar Rosa dos Ventos')),
                ('show_legend', models.BooleanField(default=True, verbose_name='Mostrar Legenda')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_config', to='maps.gisproject')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.maplayout', verbose_name='Layout Escolhido')),
            ],
            options={
                'verbose_name': 'Configuração de Mapa',
                'verbose_name_plural': 'Configurações de Mapas',
            },
        ),
        migrations.CreateModel(
            name='UploadedGISFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=maps.models.upload_to_gis_files, verbose_name='Arquivo GIS')),
                ('file_type', models.CharField(choices=[('shp', 'Shapefile'), ('kml', 'KML'), ('kmz', 'KMZ'), ('geojson', 'GeoJSON'), ('gpx', 'GPX')], max_length=10, verbose_name='Tipo de Arquivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nome Original')),
                ('file_size', models.PositiveIntegerField(verbose_name='Tamanho do Arquivo (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('geometry_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Geometria')),
                ('coordinate_system', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema de Coordenadas')),
                ('bounds_north', models.FloatField(blank=True, null=True)),
                ('bounds_south', models.FloatField(blank=True, null=True)),
                ('bounds_east', models.FloatField(blank=True, null=True)),
                ('bounds_west', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='maps.gisproject')),
            ],
            options={
                'verbose_name': 'Arquivo GIS',
                'verbose_name_plural': 'Arquivos GIS',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
